# Generated by Django 4.1.7 on 2023-04-07 15:55

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_image_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to=utils.get_upload_path_for_users),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to=utils.get_upload_path_for_users),
        ),
    ]
