# Используем официальный образ Python в качестве базового
FROM python:3.9-slim-buster

# Устанавливаем переменные окружения
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Создаем директорию для нашего приложения
WORKDIR /app

# Копируем файлы зависимостей в директорию приложения
COPY req.txt /app/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r req.txt

# Копируем весь проект в директорию приложения
COPY . /app/
