# Используем официальный образ Python в качестве базового
FROM python:3.9-slim-buster

# Устанавливаем переменные окружения для Python
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Устанавливаем рабочую директорию
WORKDIR /code

# Копируем файлы зависимостей в директорию приложения
COPY req.txt /code/

# Устанавливаем зависимости
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r req.txt

# Копируем все файлы проекта в директорию приложения
COPY . .

# Запускаем Celery worker
CMD ["celery", "-A", "core", "worker", "--loglevel=info"]
